### ISSUE TITLE
"Now playing" icon is not being updated on track change until mouseover

### ISSUE THREAD

**Issue by Suxxxit** [ciderapp/Cider-2.x#8]
Not sure if it is an environment-specific bug, but in my client (Win 11) it is a default behavior.
In 'Browse' and 'Listen Now' screens icon is not switched when next track starts to play. For this icon to be displayed on the new track, I need to move cursor over new track, and also have to move cursor over the previous track, so icon on it would disappear.
In Library, there is no visible "Now playing" icon on the track line, but it hides the 'heart' icon. If I am to assume that icon is there, but it's just invisible - behavior is the same as in 'Browse' and 'Listen Now' modes.

**Comment by cryptofyre** [comment]
Do not use this repository for Cider 1.x bugs.
